# Variable 'MOBILECENTER_OUTPUT_DIRECTORY' was defined in the Variables tab
# Variable 'MOBILECENTER_BRANCH' was defined in the Variables tab
# Variable 'MOBILECENTER_BUILD_ID' was defined in the Variables tab
# Variable 'MOBILECENTER_SOURCE_DIRECTORY' was defined in the Variables tab
# Variable 'MOBILECENTER_TRIGGER' was defined in the Variables tab
# Variable 'APPCENTER_OUTPUT_DIRECTORY' was defined in the Variables tab
# Variable 'APPCENTER_BRANCH' was defined in the Variables tab
# Variable 'APPCENTER_BUILD_ID' was defined in the Variables tab
# Variable 'APPCENTER_SOURCE_DIRECTORY' was defined in the Variables tab
# Variable 'APPCENTER_TRIGGER' was defined in the Variables tab
# Variable 'artifactVersioning.build.format' was defined in the Variables tab
# Variable 'buildScripts.toolset' was defined in the Variables tab
# Variable 'moduleName' was defined in the Variables tab
# Variable 'buildVariant' was defined in the Variables tab
# Variable 'isRoot' was defined in the Variables tab
# Variable 'runTests' was defined in the Variables tab
# Variable 'runLint' was defined in the Variables tab
# Variable 'keystorePassword' was defined in the Variables tab
# Variable 'keyAlias' was defined in the Variables tab
# Variable 'keyPassword' was defined in the Variables tab
# Variable 'keystoreFilename' was defined in the Variables tab
# Variable 'keystoreSecureFileId' was defined in the Variables tab
# Variable 'keystoreSecureFilename' was defined in the Variables tab
# Variable 'keystoreEncoded' was defined in the Variables tab
# Variable 'automaticSigning' was defined in the Variables tab
# Variable 'buildBundle' was defined in the Variables tab
# Variable 'MOBILECENTER_ANDROID_MODULE' was defined in the Variables tab
# Variable 'MOBILECENTER_ANDROID_VARIANT' was defined in the Variables tab
# Variable 'APPCENTER_ANDROID_MODULE' was defined in the Variables tab
# Variable 'APPCENTER_ANDROID_VARIANT' was defined in the Variables tab
# Variable 'SONOMA_API_SERVER' was defined in the Variables tab
# Variable 'SONOMA_API_VERSION' was defined in the Variables tab
# Variable 'VSMobileCenterUpload.ContinueIfSymbolsNotFound' was defined in the Variables tab
# Variable 'sonoma.tags' was defined in the Variables tab
name: $(Build.BuildId)
resources:
  repositories:
  - repository: self
    type: git
    ref: develop
jobs:
- job: Phase_1
  displayName: Agent job 1
  timeoutInMinutes: 30
  pool:
    vmImage: macos-10.15
  steps:
  - checkout: self
    clean: true
    submodules: recursive
    lfs: true
  - task: PowerShell@2
    displayName: Install build scripts
    continueOnError: True
    inputs:
      targetType: inline
      scriptName: ''
      script: >-
        Set-Location -Path '$(Agent.HomeDirectory)'

        Invoke-WebRequest -Uri 'https://appcenterbuildassets.azureedge.net/buildscripts/appcenter-build-assets-latest.zip' -OutFile 'appcenter-build-assets-latest.zip'

        if (Test-Path ./scripts) { Remove-Item -Path ./scripts -Force -Recurse }

        New-Item -ItemType directory -Path 'scripts' | Out-Null

        unzip -q -d 'scripts' 'appcenter-build-assets-latest.zip'

        Invoke-Expression 'bash ./scripts/init.sh'
      failOnStderr: true
  - task: ShellScript@2
    displayName: Tag build
    inputs:
      scriptPath: $(Agent.HomeDirectory)/scripts/emit-tags.sh
      args: $(sonoma.tags)
  - task: Gradle@1
    displayName: Gradle Task
    inputs:
      tasks: 'clean :app:assembleRelease '
      options: -DAPPCENTER_KEYSTORE_PASSWORD="$(keystorePassword)" -DMOBILECENTER_KEYSTORE_PASSWORD="$(keystorePassword)" -DAPPCENTER_KEYSTORE_FILE_ID="$(keystoreFilename)" -DMOBILECENTER_KEYSTORE_FILE_ID="$(keystoreFilename)" -DAPPCENTER_KEY_ALIAS="$(keyAlias)" -DMOBILECENTER_KEY_ALIAS="$(keyAlias)" -DAPPCENTER_KEY_PASSWORD="$(keyPassword)" -DMOBILECENTER_KEY_PASSWORD="$(keyPassword)" -DAPPCENTER_BUILD_VERSION="$(Build.BuildNumber)" -DMOBILECENTER_BUILD_VERSION="$(Build.BuildNumber)"
      jdkArchitecture: x86
      publishJUnitResults: false
      sqAnalysisBreakBuildIfQualityGateFailed: false
  - task: ShellScript@2
    name: appcenter_android_postprocess_output
    displayName: Android Postprocess
    inputs:
      scriptPath: $(Agent.HomeDirectory)/scripts/android-postprocess.sh
      args: $(build.sourcesdirectory)/app/build/outputs/apk
  - task: AndroidSigning@3
    displayName: Sign APK
    inputs:
      files: $(build.sourcesdirectory)/app/build/**/*.apk
      keystoreFile: $(keystoreSecureFileId)
      keystorePass: $(keystorePassword)
      keystoreAlias: $(keyAlias)
      keyPass: $(keyPassword)
      apksignerArguments: -verbose
  - task: CopyFiles@2
    displayName: Copy build files to staging
    inputs:
      SourceFolder: $(build.sourcesdirectory)/app/build/outputs
      Contents: apk/**/*.apk
      TargetFolder: $(build.artifactstagingdirectory)/build
      OverWrite: true
      flattenFolders: true
  - task: CopyFiles@2
    displayName: Copy mapping files to staging
    inputs:
      SourceFolder: $(build.sourcesdirectory)/app/build/outputs
      Contents: mapping/**/mapping.txt
      TargetFolder: $(build.artifactstagingdirectory)/mapping
      OverWrite: true
      flattenFolders: true
  - task: PublishBuildArtifacts@1
    displayName: Publish build
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)/build
      ArtifactName: build
  - task: PublishBuildArtifacts@1
    displayName: Publish mapping
    condition: and(succeeded(), startsWith(variables['appcenter_android_postprocess_output.mapping'], true))
    continueOnError: True
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)/mapping
      ArtifactName: mapping
  - task: AppCenterDistribute@3
    displayName: Create distribution
    condition: and(succeeded(), ne(variables['Build.Reason'], 'pullRequest'))
    inputs:
      serverEndpoint: bf411334-1928-47f9-89e9-b80485a230ea
      appSlug: v-ivankostic/android-test
      destinationGroupIds: 38a19e3e-f623-4cb1-8f63-5e21ed8d2de1
      isSilent: True
      releaseNotesInput: $(lastCommitMessage)
      app: $(build.artifactstagingdirectory)/build/**/*.apk
      symbolsType: Android
      mappingTxtPath: $(build.artifactstagingdirectory)/mapping/**/mapping.txt
      nativeLibrariesPath: $(build.sourcesdirectory)/**/*.so
...
